name: CI Pipeline # This is the name of the pipeline

on:
  push: # Trigger the pipeline on push events
    branches:
      - main # Specify the branch to watch for changes

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
    - name: Checkout code # Step to check out the code
      uses: actions/checkout@v2

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        ls -R
    - name: Make scripts executable # Step to make scripts executable
      run: chmod +x bash-scripting/scripting/*.sh

    - name: Run scripts # Step to run the bash scripts
      run: |
        set -e # Exit immediately if a command exits with a non zero status
        ./bash-scripting/scripting/check-dir.sh ./bash-scripting/scripting # Run a specific script
        ./bash-scripting/scripting/dir-file-loop.sh ./bash-scripting/scripting # Loop over all files in the specified directory