name: CI Pipeline # This is the name of the pipeline

on:
  push: # Trigger the pipeline on push events
    branches:
      - main # Specify the branch to watch for changes

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
    - name: Checkout code # Step to check out the code
      uses: actions/checkout@v2

    - name: Set up Bash # Placeholder step for setting up Bash
      run: echo "Bash is set up"

    - name:
      run: |
        echo "Current directory: $(pwd)"
        ls -R

    - name: Run scripts # Step to run the bash scripts
      run: |
        chmod +x bash-scripting/scripting/*.sh # Make all scripts executable
        ./bash-scripting/scripting/check-dir.sh ./bash-scripting/scripting # Run a specific script