name: CI for directory-check.sh

on:
  workflow_dispatch:

jobs: # comment test
  test-directory-check:
    runs-on: ubuntu-latest
    continue-on-error: true # <- Let other matrix jobs run despite failure ( will stop on first failure )
    strategy:
      matrix:
        dir:
          - bash-scripting/scripting
          - bash-scripting/invalid-dir
          - /tmp
          - /nonexistent
    env:
      TARGET_DIR: ${{ matrix.dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x bash-scripting/scripting/directory-check.sh

      - name: Run directory-check.sh
        id: run_directories
        run: bash bash-scripting/scripting/directory-check.sh

      - name: Set formatted directory name
        run: |
          FORMATTED_DIR="${{ matrix.dir }}"
          FORMATTED_DIR="${FORMATTED_DIR//\//-}"
          echo "FORMATTED_DIR=$FORMATTED_DIR" >> $GITHUB_ENV

      - name: Upload log artifact
        if: steps.run_directories.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: directory-check-log-${{ env.FORMATTED_DIR }}
          path: bash-scripting/bash-logs/directory_check.log

  summarize-results:
    needs: test-directory-check
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download all logs
        uses: actions/download-artifact@v4
        with:
          path: ./all-logs

      - name: Summarize logs
        run: |
          echo "Summary of directory-check errors:"
          grep -rH "\[ERROR\]" ./all-logs || echo "No errors found in logs."