name: Run script example

on:
  workflow_dispatch:
#on:
  #push:   # Triggers on every push to any branch
    #branches:
      #- main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x script.sh
        
      - name: Execute script.sh
        run: ./script.sh
      